### ISSUE TITLE
schedule kick off meeting

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/FisheryConditionLinks#2]
Kick off meeting to be scheduled by last week in April, 2020 / 1st week of May
A doodle poll will be sent around

Things to discuss
1. Decide on group of species for focus
2. Decide on number of sub-projects (and therefore github folders). For example, fish condition, social-economic links to condition, primary production links to condition
3. Decide who is in each sub-group

See [notes](https://drive.google.com/open?id=1hytxCpnvXXZpZnkwALyRz_aiS3pO94sZ2n1meOM1KdI)

**Comment by Laurels1** [comment]
The Kick-off meeting is scheduled for May 5th from 10-11am
